name: Deploy React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: bun install

      - name: Build the app
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP_ADDRESS: ${{ secrets.VPS_IP_ADDRESS }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r dist/* $VPS_USERNAME@$VPS_IP_ADDRESS:$VPS_PATH
          ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_IP_ADDRESS 'sudo systemctl restart nginx'
